"""Congress Trading Streamlit dashboard — shared utilities."""

from __future__ import annotations

from ..db import get_connection, init_db

from .analytics import (
    add_trade_categories,
    bipartisan_tickers,
    call_put_monthly,
    classify_option_side,
    detect_coordinated_trades,
    member_ticker_breakdown,
    normalize_party,
    ticker_member_breakdown,
    volume_anomalies,
)
from .charts import (
    _build_member_activity_timeline,
    _build_member_cumulative_notional_chart,
    _build_mix_chart,
    _build_rank_chart,
    _build_ticker_3d_figure,
    _build_ticker_member_timeline,
    _build_time_series_chart,
    _ticker_timeline_color_key_html,
    build_price_overlay_figure,
)
from .components import (
    _copy,
    _metric_card,
    _render_empty_state,
    _render_hero,
    _render_section_intro,
)
from .constants import (
    DASHBOARD_COPY,
    DEFAULT_TRANSACTION_FILTER_START,
    NORMALIZED_EXPORT_PATH,
    REVIEW_COLUMNS,
    REVIEW_EXPORT_PATH,
    SQLITE_REVIEW_QUERY,
    SQLITE_TRANSACTION_QUERY,
    THEME,
    TRANSACTION_COLUMNS,
)
from .data import (
    _download_bytes,
    _format_currency,
    _polygon_daily_bar_cache_size,
    _prepare_review,
    _prepare_transactions,
    load_polygon_bars,
    load_review_queue,
    load_transactions,
    load_transactions_cached,
    merge_polygon_pnl_cached_columns,
    transaction_type_display_label,
    transaction_type_filter_option,
)
from .filters import _apply_filters, _apply_filters_fragment
from .session import get_dashboard_context, render_slice_hero_and_kpis, setup_dashboard_session
from .styles import _altair_readability, _inject_styles, _style_dataframe_buy_sell

__all__ = [
    "DASHBOARD_COPY",
    "DEFAULT_TRANSACTION_FILTER_START",
    "NORMALIZED_EXPORT_PATH",
    "REVIEW_COLUMNS",
    "REVIEW_EXPORT_PATH",
    "SQLITE_REVIEW_QUERY",
    "SQLITE_TRANSACTION_QUERY",
    "THEME",
    "TRANSACTION_COLUMNS",
    "_altair_readability",
    "_apply_filters",
    "_apply_filters_fragment",
    "_build_member_activity_timeline",
    "_build_member_cumulative_notional_chart",
    "_build_mix_chart",
    "_build_rank_chart",
    "_build_ticker_3d_figure",
    "_build_ticker_member_timeline",
    "_build_time_series_chart",
    "_copy",
    "_download_bytes",
    "_format_currency",
    "_inject_styles",
    "_metric_card",
    "_polygon_daily_bar_cache_size",
    "_prepare_review",
    "_prepare_transactions",
    "_render_empty_state",
    "_render_hero",
    "_render_section_intro",
    "_style_dataframe_buy_sell",
    "_ticker_timeline_color_key_html",
    "add_trade_categories",
    "bipartisan_tickers",
    "build_price_overlay_figure",
    "call_put_monthly",
    "classify_option_side",
    "detect_coordinated_trades",
    "get_connection",
    "get_dashboard_context",
    "init_db",
    "load_polygon_bars",
    "load_review_queue",
    "load_transactions",
    "load_transactions_cached",
    "member_ticker_breakdown",
    "merge_polygon_pnl_cached_columns",
    "normalize_party",
    "render_slice_hero_and_kpis",
    "setup_dashboard_session",
    "ticker_member_breakdown",
    "transaction_type_display_label",
    "transaction_type_filter_option",
    "volume_anomalies",
]
