/** Page copy strings for the React dashboard. */
export const COPY = {
  review: {
    kicker: "Review Queue",
    title: "Triage unresolved records",
    copy: "These rows still require manual confirmation or a better asset resolution. Treat this tab as the backlog that determines analysis quality.",
    recordsCard: "Records needing review",
    byReason: "By reason",
    byStatus: "By status",
    reasonCaption: "How many review-queue rows per reason code.",
    statusCaption: "How many review-queue rows per status (open, …).",
    summaryTable: "Summary",
    transactionDetail: "Full transaction detail",
  },
  members: {
    kicker: "Members",
    title: "Politician profiles & leaderboard",
    copy: "Leaderboard, per-member KPIs, by-ticker breakdown, and activity over time for the active period slice.",
    leaderboard: "Leaderboard",
    profile: "Member profile",
    allTrades: "All trades",
    committeeRelevant: "Committee relevant",
    byTicker: "By ticker",
    activity: "Activity over time",
    topTickers: "Top tickers by trade count",
    committeeCard: "Committee-relevant trades",
  },
  tickers: {
    kicker: "Tickers",
    title: "Stock-level congressional activity",
    copy: "Pick a symbol to see who traded it, price overlay, member timeline, and cumulative net exposure.",
    whoTraded: "Who traded this ticker",
    priceOverlay: "Price & trade overlay",
    memberTimeline: "Member timeline",
    cumulativeExposure: "Net disclosed dollars over time",
    cumulativeGuideTitle: "How to read this chart",
    cumulativeGuideLines:
      "Colored line = one member · Step up = buy · Step down = sell · Flat = no new trades · Dashed $0 line = buys and sells balance out so far",
    cumulativeGuideNote:
      "Congress filings report dollar ranges (e.g. $1k–$15k), not shares. This is a rough activity proxy, not portfolio value or current holdings.",
    noPolygon: "No Polygon cache data for this ticker — run python -m src.main warm-polygon-price-cache",
  },
  patterns: {
    kicker: "Patterns",
    title: "Signals & coordination",
    copy: "Committee overlap, coordinated trades, call/put trends, disclosure spikes, and bipartisan activity.",
    committee: "Committee relevance",
    coordinated: "Coordinated buying / selling",
    callPut: "Call vs put trends",
    callPutNote: ">1 means more calls than puts that month.",
    tickerFilter: "Filter call/put chart by ticker (optional)",
    volumeSpikes: "Disclosure spikes",
    volumeCaption: "≥3 recent disclosures AND recent_per_month ≥ 2× prior_per_month",
    bipartisan: "Bipartisan trades",
  },
} as const;
